environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0

install:
  - choco install winfsp

build_script:
  - gradlew.bat build --no-daemon

test_script:
  - gradlew.bat check --no-daemon

cache:
  - C:\Users\appveyor\.gradle